import type { Metadata } from "next";
import Navbar from "../components/Navbar/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className="w-full text-textColor">
        <Navbar />
        <main className="w-4/5 mx-auto">{children}</main>
      </body>
    </html>
  );
}
